name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
  REGION: ${{ secrets.GOOGLE_CLOUD_REGION }}
  REGISTRY_NAME: ${{ secrets.ARTIFACT_REGISTRY_NAME }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout Dockerfile repository
        uses: actions/checkout@v2
        with:
          repository: masaru-nohara/are-you-free-infra
          path: are-you-free-infra
          ref: main
          token: ${{ secrets.GH_DEPLOY_TO_CLOUDRUN_TOKEN }}

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          registry_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build
        run: docker build --platform linux/amd64 -f are-you-free-infra/deploys/production/web/Dockerfile -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Push
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Deploy
        run: gcloud run deploy are-you-free-prd-web-cloud-run --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} --platform managed --region ${{ env.REGION }} --platform managed --port 5173
